name: Deploy Frontend to Backend Prod

on:
  push:
    branches: [main]

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          path: frontend
      - name: Install Packages
        run: |
          cd frontend
          npm i
      - name: Build website
        run: |
          cd frontend
          npm run build
        
  Pull-request-into-backend:
    runs-on: self-hosted
    needs: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          repository: ZGameLogic/Minecraft-Server-Utility-Backend
          ref: development
          path: backend
      - name: Add Build to Backend
        run: echo d | xcopy /j /y /s "frontend\build" "backend\src\main\resources\static"
#      - name: Commit Backend Code
#        run: |
#          cd backend
#          git config --global user.name 'zabory'
#          git config --global user.email 'benshabowski@gmail.com'
#          git remote set-url origin  https://github.com/ZGameLogic/Minecraft-Server-Utility-Backend.git
#          git add -A
#          git commit -m "Updating backend with new frontend UI automatically"
#          git push